import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';

const source = readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const ledger = JSON.parse(readFileSync(new URL('../data/bet-ledger.json', import.meta.url), 'utf8'));
const racing = JSON.parse(readFileSync(new URL('../data/races.json', import.meta.url), 'utf8'));
const appElement = {innerHTML:''};
const document = {querySelector:selector => selector==='#app'?appElement:null, querySelectorAll:()=>[]};
const sandbox = {document,console,fetch:async()=>{throw new Error('Unexpected network call')}};
const boot = source.indexOf('\nload(true).then(loadLive);');
assert.ok(boot > 0,'Browser bootstrap present');
const app = vm.runInNewContext(source.slice(0,boot)+'\n;({state,settlement,trackerStats,render,exoticSummary,lucky15Calc})',sandbox);
app.state.ledger=ledger;
app.state.data=racing;
const stats=app.trackerStats(ledger.entries);
assert.equal(stats.known,22,'Known finishes');
assert.equal(stats.winCount,6,'Winning picks');
assert.equal(stats.settled,23,'Fully settled bets');
assert.equal(stats.openStake,50,'Outstanding stakes');
assert.equal(stats.totalStake,280,'Total paper stakes');
assert.equal(app.settlement(ledger.entries.find(e=>e.horse==='King Gris')).returnAmount,10,'King Gris NR £10 refund');
assert.equal(ledger.entries.find(e=>e.horse==='Aighear').settlementOdds,'4/7','Aighear confirmed SP');
assert.equal(ledger.entries.find(e=>e.horse==='Rattledelatch').settlementOdds,'1/1','Rattledelatch confirmed SP');
assert.equal(app.settlement(ledger.entries.find(e=>e.horse==='Toralou')).status,'lost','Toralou confirmed sixth place is a losing EW bet');
assert.equal(app.settlement(ledger.entries.find(e=>e.horse==='Pampar Lady')).status,'lost','Pampar Lady confirmed eleventh place is losing');
assert.equal(app.settlement(ledger.entries.find(e=>e.horse==='Eagle Storm')).status,'lost','Eagle Storm sixth place loses £10 each-way');
assert.equal(app.settlement(ledger.entries.find(e=>e.horse==='War Howl')).status,'lost','War Howl eleventh place loses £10 each-way');
assert.equal(ledger.entries.filter(e=>!e.result&&e.date==='2026-10-08').length,0,'All 8 October picks have recorded outcomes');
assert.equal(app.settlement(ledger.entries.find(e=>e.horse==='Ratemenow')).status,'lost','Ratemenow second in win-only market is a loss');
assert.equal(ledger.entries.length,28,'23 historical bets and 5 new singles');
assert.equal(racing.todaySelections.length,2,'Only two main win selections');
assert.equal(racing.todaySelections.filter(x => x.restoredFromPreviousVersion).length,0,'Earlier picks removed');
assert.equal(ledger.entries.filter(x => x.restoredFromPreviousVersion).length,0,'Earlier bets removed');
assert.equal(ledger.entries.find(x=>x.horse==='Aighear')?.result?.position,1,'Aighear win preserved');
assert.equal(ledger.entries.find(x=>x.horse==='Rattledelatch')?.result?.position,1,'Rattledelatch win preserved');
assert.equal(Math.round(stats.profit*100)/100,-15.76,'Settled P/L');
assert.equal(Math.round((1000-stats.totalStake+stats.totalReturn-app.exoticSummary().stake)*100)/100,904.24,'Available bank');
assert.equal(app.settlement({betType:'win',winStake:10,placeStake:0,result:{status:'NR'}}).returnAmount,10,'Refund NR');
assert.equal(app.settlement({betType:'win',winStake:10,placeStake:0,result:{status:'PU'}}).status,'lost','PU is a loss');
assert.equal(app.settlement({betType:'each-way',winStake:5,placeStake:5,runnerCount:8,selectionOdds:'20/1',result:{position:2}}).returnAmount,30,'Quarter odds place payout');
assert.equal(app.settlement({betType:'each-way',winStake:5,placeStake:5,runnerCount:7,selectionOdds:'20/1',result:{position:3}}).status,'lost','Seven runners pays two places');
assert.equal(app.settlement({betType:'each-way',winStake:5,placeStake:5,runnerCount:4,selectionOdds:'20/1',result:{position:2}}).status,'lost','Four runners pays first only');
assert.equal(app.settlement({betType:'each-way',winStake:5,placeStake:5,runnerCount:8,selectionOdds:'20/1',result:{position:1}}).returnAmount,135,'Win plus place winnings');
assert.equal(app.settlement({betType:'each-way',winStake:5,placeStake:5,runnerCount:null,selectionOdds:'20/1',result:{position:2}}).status,'unpriced','Unknown field size cannot settle');

assert.equal(racing.snapshotDate,'2026-10-09','Friday card is published');
assert.equal(racing.midshotsToday.length,2,'Only two midshot selections');
assert.equal(racing.longshotsToday.length,1,'Only one speculative longshot');
assert.equal(racing.racecardLinks.length,6,'All six meetings link to full declared runners');
assert.equal(app.exoticSummary().pendingStake,30,'EW Lucky15 paper stake held separately');
assert.equal(app.exoticSummary().tickets[0].legs.length,4,'Four Lucky15 horses');
const unitVoid=JSON.parse(JSON.stringify(ledger.lucky15Tickets[0]));
unitVoid.date='1900-01-01';
for(const leg of unitVoid.legs)leg.result={status:'NR'};
assert.equal(app.lucky15Calc(unitVoid).returnAmount,30,'Four void legs refund all 30 Lucky15 lines');
for(const leg of unitVoid.legs)leg.result={position:6};
assert.equal(app.lucky15Calc(unitVoid).returnAmount,0,'Four unplaced legs lose all Lucky15 lines');
app.render();
assert.match(appElement.innerHTML,/Profit & strike-rate tracker/,'Tracker rendered');
assert.match(appElement.innerHTML,/Win strike rate/,'Win strike rate displayed');
assert.match(appElement.innerHTML,/Each-way place rate/,'EW strike rate displayed');
assert.match(appElement.innerHTML,/data-refresh-results/,'Manual refresh button is present');
app.state.view='lucky15';
app.render();
assert.match(appElement.innerHTML,/Each-way Lucky 15/,'EW Lucky15 page');
assert.match(appElement.innerHTML,/Flann Sunna/,'Standalone Lucky15 leg');
app.state.view='racecards';
app.render();
assert.match(appElement.innerHTML,/All runners/,'Full runner listing linked');
assert.match(appElement.innerHTML,/horseracing.net\/york\/09-10-26/,'Meeting links present');
app.state.view='history';
app.render();
assert.match(appElement.innerHTML,/Results history/,'Latest results history accessible');
assert.doesNotMatch(appElement.innerHTML,/Blissful Bonita|Lady Of Clover/,'Removed earlier selections absent');

assert.ok(appElement.innerHTML.includes('sportinglife.com/racing/fast-results'),'Fast results reference is present');
assert.match(appElement.innerHTML,/£904\.24/,'Bank shown correctly');
assert.match(appElement.innerHTML,/-£15\.76/,'Settled P/L shown correctly');
console.log('PASS: cumulative bankroll, new card, EW Lucky15, racecard links, settlement rules and history');
